service: awswebsocketchat
frameworkVersion: "^1.71.3"

custom:
  currentStage: ${opt:stage, self:provider.stage}
  lambdaRunTime: python3.6
  socketConnectionsTableName: socketConnections-#{AWS::AccountId}-${self:custom.currentStage}
  socketChannelsTableName: socketChannels-#{AWS::AccountId}-${self:custom.currentStage}

provider:
  name: aws
  iamManagedPolicies:
  - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
  runtime: ${self:custom.lambdaRunTime}
  versionFunctions: false
  region: eu-west-2
  timeout: 29

plugins:
  - serverless-pseudo-parameters
package:
  individually: true
  exclude:
    - "lib/**"
    - "node_modules/**"

layers:
  pythonPackageLayer:
    path: lib
    name: Python-Package-layer
    description: Python Package layer
    compatibleRuntimes:
      - ${self:custom.lambdaRunTime}

functions:
  connectHandler:
    handler: connect_handler.handle
    events:
      - websocket: $connect
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      SOCKET_CONNECTIONS_TABLE_NAME: ${self:custom.socketConnectionsTableName}
      SOCKET_CHANNELS_TABLE_NAME: ${self:custom.socketChannelsTableName}

  disconnectHandler:
    handler: disconnect_handler.handle
    events:
      - websocket: $disconnect
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      SOCKET_CONNECTIONS_TABLE_NAME: ${self:custom.socketConnectionsTableName}
      SOCKET_CHANNELS_TABLE_NAME: ${self:custom.socketChannelsTableName}

  onMessageHandler:
    handler: on_message_handler.handle
    events:
      - websocket:
          route: onMessage
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      SOCKET_CONNECTIONS_TABLE_NAME: ${self:custom.socketConnectionsTableName}
      SOCKET_CHANNELS_TABLE_NAME: ${self:custom.socketChannelsTableName}

  onSubscribeHandler:
    handler: on_subscribe_handler.handle
    events:
      - websocket:
          route: onSubscribe
    layers:
      - { Ref: PythonPackageLayerLambdaLayer }
    environment:
      SOCKET_CONNECTIONS_TABLE_NAME: ${self:custom.socketConnectionsTableName}
      SOCKET_CHANNELS_TABLE_NAME: ${self:custom.socketChannelsTableName}

resources:
  Resources:
    socketConnectionsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.socketConnectionsTableName}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true
    socketChannelsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.socketChannelsTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true
